/// @filename JuceHeader.h
/// @brief OpenMini standalone specific header
/// @author gm
/// @copyright gm 2013
///
/// This file is part of OpenMini
///
/// OpenMini is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
///
/// OpenMini is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
///
/// You should have received a copy of the GNU General Public License
/// along with OpenMini.  If not, see <http://www.gnu.org/licenses/>.


// This file is generated by Juce, that's why we do not try too hard
// applying our coding style here - except for the copyright

#ifndef __APPHEADERFILE_OQ1Z0T__
#define __APPHEADERFILE_OQ1Z0T__

#include "AppConfig.h"
#include "modules/juce_audio_basics/juce_audio_basics.h"
#include "modules/juce_audio_devices/juce_audio_devices.h"
#include "modules/juce_audio_utils/juce_audio_utils.h"
#include "modules/juce_audio_processors/juce_audio_processors.h"
#include "modules/juce_core/juce_core.h"
#include "modules/juce_data_structures/juce_data_structures.h"
#include "modules/juce_events/juce_events.h"
#include "modules/juce_graphics/juce_graphics.h"
#include "modules/juce_gui_basics/juce_gui_basics.h"
#include "modules/juce_gui_extra/juce_gui_extra.h"

#if ! DONT_SET_USING_JUCE_NAMESPACE
 // If your code uses a lot of JUCE classes, then this will obviously save you
 // a lot of typing, but can be disabled by setting DONT_SET_USING_JUCE_NAMESPACE.
 using namespace juce;
#endif

namespace ProjectInfo
{
    const char* const  projectName    = "OpenMini";
    const char* const  versionString  = "1.0.0";
    const int          versionNumber  = 0x10000;
}

// Stealing these definitions from the plugin JuceHeader.h file allows us
// to use the exact same editor and processor source files:
// no modifications required at all
#define JucePlugin_MaxNumInputChannels 0
#define JucePlugin_MaxNumOutputChannels 1
#define JucePlugin_Name "OpenMini"

#endif   // __APPHEADERFILE_OQ1Z0T__
