/// @filename MainApplication.cpp
/// @brief OpenMini standalone main application
/// @author gm
/// @copyright gm 2013
///
/// This file is part of OpenMini
///
/// OpenMini is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
///
/// OpenMini is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
///
/// You should have received a copy of the GNU General Public License
/// along with OpenMini.  If not, see <http://www.gnu.org/licenses/>.


// This file is NOT generated by Juce (at least not after the first time),
// That's why we apply our coding style here

#include "openmini/implementation/standalone/MainApplication.h"

MainApplication::MainApplication()
    : plugin_(getApplicationName(), juce::Colours::white, nullptr) {
  // Nothing to do here for now
}

const juce::String MainApplication::getApplicationName() {
  return ProjectInfo::projectName;
}
const juce::String MainApplication::getApplicationVersion() {
  return ProjectInfo::versionString;
}
bool MainApplication::moreThanOneInstanceAllowed() {
  return true;
}

void MainApplication::initialise(const juce::String& commandLine) {
  plugin_.resetFilter();
  plugin_.setVisible(true);
}

void MainApplication::shutdown() {
  // Nothing to do here!
}

void MainApplication::systemRequestedQuit() {
  quit();
}

void MainApplication::anotherInstanceStarted(const juce::String& commandLine) {
  // Nothing to do here!
}
