/// @filename PluginEditor.cpp
/// @brief OpenMini plugin editor (UI & control)
/// @author gm
/// @copyright gm 2013
///
/// This file is part of OpenMini
///
/// OpenMini is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
///
/// OpenMini is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
///
/// You should have received a copy of the GNU General Public License
/// along with OpenMini.  If not, see <http://www.gnu.org/licenses/>.


// This file is NOT generated by Juce (at least not after the first time),
// That's why we apply our coding style here

// std::floor
#include <cmath>

#include "openmini/implementation/common/PluginEditor.h"

#include "openmini/src/common.h"

OpenMiniAudioProcessorEditor::OpenMiniAudioProcessorEditor(
    OpenMiniAudioProcessor* owner)
    : AudioProcessorEditor(owner),
      owner_(owner),
      keyboard_(owner->keyboard_state_,
                juce::MidiKeyboardComponent::horizontalKeyboard) {
  // For some reason Juce keyboard is one octave higher...
  keyboard_.setAvailableRange(openmini::kMinKeyNote + 12,
                              openmini::kMaxKeyNote + 12);
  keyboard_.setKeyWidth(std::floor(static_cast<float>(kMainWindowSizeX)
                        / ((openmini::kMaxKeyNote - openmini::kMinKeyNote)
                        // remember, 5 keys out of 12 are black!
                        * 7.0f / 12.0f)));
  addAndMakeVisible(&keyboard_);
  // This is where our plugin's editor size is set.
  setSize(kMainWindowSizeX, kMainWindowSizeY);
}

OpenMiniAudioProcessorEditor::~OpenMiniAudioProcessorEditor() {
}

void OpenMiniAudioProcessorEditor::paint(Graphics& g) {
  g.fillAll(Colours::white);
  const int kKeyboardHeight(this->getHeight() / 4);
  const int kKeyboardTop(this->getHeight() - kKeyboardHeight);
  keyboard_.setBounds(0, kKeyboardTop, this->getWidth(), kKeyboardHeight);
}

OpenMiniAudioProcessor* OpenMiniAudioProcessorEditor::getProcessor() const {
  return static_cast<OpenMiniAudioProcessor*>(getAudioProcessor());
}
