/// @filename Widget.h
/// @brief OpenMini generic widget component
/// @author gm
/// @copyright gm 2013
///
/// This file is part of OpenMini
///
/// OpenMini is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
///
/// OpenMini is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
///
/// You should have received a copy of the GNU General Public License
/// along with OpenMini.  If not, see <http://www.gnu.org/licenses/>.


// This file is NOT generated by Juce (at least not after the first time),
// That's why we apply our coding style here


#ifndef OPENMINI_PLUGIN_COMMON_WIDGET_H_
#define OPENMINI_PLUGIN_COMMON_WIDGET_H_

#include "JuceHeader.h"

#include "openmini/src/synthesizer/parameter_meta.h"

// Using declarations for OpenMini parameters
using openmini::synthesizer::ParameterMeta;

/// @brief Widget generic component
///
/// This component is a "generic" one, whose implementation details
/// such as actual look and feel etc. is fixed at instantiation,
/// based on the parameter metadata it is supposed to represent.
class Widget : public juce::Slider {
 public:
  explicit Widget(const ParameterMeta& param_meta);
  ~Widget();

  void paint(juce::Graphics& g);
  void resized();

 private:
  juce::DrawableText label_;
};

#endif  // OPENMINI_PLUGIN_COMMON_WIDGET_H_
