/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "JuceHeader.h"
#include "PluginProcessor.h"


static const int kMainWindowSizeX(800);
static const int kMainWindowSizeY(600);

//==============================================================================
/**
*/
class OpenMiniAudioProcessorEditor  : public AudioProcessorEditor,
                                      public Button::Listener
{
public:
    OpenMiniAudioProcessorEditor (OpenMiniAudioProcessor* ownerFilter);
    ~OpenMiniAudioProcessorEditor();

    OpenMiniAudioProcessor* getProcessor() const;

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);

    virtual void buttonClicked(Button*);
    virtual void buttonStateChanged(Button* button);

private:
  juce::ScopedPointer<juce::TextButton> keyboard_;
  OpenMiniAudioProcessor* owner_;
};


#endif  // PLUGINEDITOR_H_INCLUDED
